%% Initialization code
function varargout = NacelleDesign(varargin)
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
                   'gui_Singleton',  gui_Singleton, ...
                   'gui_OpeningFcn', @NacelleDesign_OpeningFcn, ...
                   'gui_OutputFcn',  @NacelleDesign_OutputFcn, ...
                   'gui_LayoutFcn',  [] , ...
                   'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end
if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end

%% Opening function
function NacelleDesign_OpeningFcn(hObject, eventdata, handles, varargin)

% Get input
handles.Nacelle_Length = varargin{1};
handles.Nacelle_Diameter = varargin{2};
handles.Nacelle_Mass = varargin{4};
handles.Hub_Mass = varargin{5};
handles.Hub_Overhang = varargin{6};
handles.Hub_Height = varargin{7};
handles.Shaft_Tilt = varargin{9};
handles.Nosecone_Length = varargin{10};
handles.Blade_Chord = varargin{11};
handles.Tower_OuterDiameter = varargin{12};
handles.NBlades = varargin{13};
handles.Blade_Cone = varargin{14};
handles.Input = varargin(1:10);

% Update input fields
set(handles.Nacelle_Length_textbox, 'String', num2str(handles.Nacelle_Length));
set(handles.Nacelle_Diameter_textbox, 'String', num2str(handles.Nacelle_Diameter));
set(handles.Nacelle, 'Value', varargin{3});
set(handles.Nacelle_Mass_textbox, 'String', num2str(handles.Nacelle_Mass));
set(handles.Hub_Mass_textbox, 'String', num2str(handles.Hub_Mass));
set(handles.Hub_Overhang_textbox, 'String', num2str(handles.Hub_Overhang));
set(handles.Hub_Height_textbox, 'String', num2str(handles.Hub_Height));
set(handles.Hub, 'Value', varargin{8});
set(handles.Shaft_Tilt_textbox, 'String', num2str(handles.Shaft_Tilt));
set(handles.Nosecone_Length_textbox, 'String', num2str(handles.Nosecone_Length));

% Update handles structure
guidata(hObject, handles);

% Halt window
uiwait(handles.NacelleDesign);

%% Closing function
function NacelleDesign_CloseRequestFcn(hObject, eventdata, handles)
button = questdlg('Save changes?');
if strcmp(button, 'Yes')
    handles.Save = true;
    guidata(hObject, handles);
    uiresume(hObject);
elseif strcmp(button, 'No')
    handles.Save = false;
    guidata(hObject, handles);
    uiresume(hObject);
end

%% Save button
function Apply_Callback(hObject, eventdata, handles)
handles.Save = true;
guidata(hObject, handles);
uiresume(handles.NacelleDesign);

%% Cancel button
function Cancel_Callback(hObject, eventdata, handles)
handles.Save = false;
guidata(hObject, handles);
uiresume(handles.NacelleDesign);

%% Output function
function varargout = NacelleDesign_OutputFcn(hObject, eventdata, handles) 

% Set output
if handles.Save
    varargout{1} = str2double(get(handles.Nacelle_Length_textbox, 'String'));
    varargout{2} = str2double(get(handles.Nacelle_Diameter_textbox, 'String'));
    varargout{3} = get(handles.Nacelle, 'Value');
    varargout{4} = str2double(get(handles.Nacelle_Mass_textbox, 'String'));
    varargout{5} = str2double(get(handles.Hub_Mass_textbox, 'String'));
    varargout{6} = str2double(get(handles.Hub_Overhang_textbox, 'String'));
    varargout{7} = str2double(get(handles.Hub_Height_textbox, 'String'));
    varargout{8} = get(handles.Hub, 'Value');
    varargout{9} = str2double(get(handles.Shaft_Tilt_textbox, 'String'));
    varargout{10} = str2double(get(handles.Nosecone_Length_textbox, 'String'));
else
    varargout = handles.Input;
end

% Close figure
delete(hObject)

%% Nacelle length - text box
function Nacelle_Length_textbox_Callback(hObject, eventdata, handles)
if str2double(get(hObject,'String')) < 0
    set(hObject, 'String', '0')
elseif isnan(str2double(get(hObject,'String')))
    set(hObject, 'String', num2str(handles.Nacelle_Length))
end
handles.Nacelle_Length = str2double(get(hObject,'String'));
guidata(hObject, handles);
function Nacelle_Length_textbox_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

%% Nacelle diameter - text box
function Nacelle_Diameter_textbox_Callback(hObject, eventdata, handles)
if str2double(get(hObject,'String')) < 0
    set(hObject, 'String', '0')
elseif isnan(str2double(get(hObject,'String')))
    set(hObject, 'String', num2str(handles.Nacelle_Diameter))
end
handles.Nacelle_Diameter = str2double(get(hObject,'String'));
guidata(hObject, handles);
function Nacelle_Diameter_textbox_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

%% Nacelle type - dropdown
function Nacelle_Callback(hObject, eventdata, handles)
function Nacelle_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

%% Nacelle mass - text box
function Nacelle_Mass_textbox_Callback(hObject, eventdata, handles)
if str2double(get(hObject,'String')) < 0
    set(hObject, 'String', '0')
elseif isnan(str2double(get(hObject,'String')))
    set(hObject, 'String', num2str(handles.Nacelle_Mass))
end
handles.Nacelle_Mass = str2double(get(hObject,'String'));
guidata(hObject, handles);
function Nacelle_Mass_textbox_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

%% Hub mass - text box
function Hub_Mass_textbox_Callback(hObject, eventdata, handles)
if str2double(get(hObject,'String')) < 0
    set(hObject, 'String', '0')
elseif isnan(str2double(get(hObject,'String')))
    set(hObject, 'String', num2str(handles.Hub_Mass))
end
handles.Hub_Mass = str2double(get(hObject,'String'));
guidata(hObject, handles);
function Hub_Mass_textbox_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

%% Hub overhang - text box
function Hub_Overhang_textbox_Callback(hObject, eventdata, handles)
if str2double(get(hObject,'String')) < 0
    set(hObject, 'String', '0')
elseif isnan(str2double(get(hObject,'String')))
    set(hObject, 'String', num2str(handles.Hub_Overhang))
end
handles.Hub_Overhang = str2double(get(hObject,'String'));
guidata(hObject, handles);
function Hub_Overhang_textbox_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

%% Hub height - text box
function Hub_Height_textbox_Callback(hObject, eventdata, handles)
if str2double(get(hObject,'String')) < 0
    set(hObject, 'String', '0')
elseif isnan(str2double(get(hObject,'String')))
    set(hObject, 'String', num2str(handles.Hub_Height))
end
handles.Hub_Height = str2double(get(hObject,'String'));
guidata(hObject, handles);
function Hub_Height_textbox_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

%% Hub type - dropdown
function Hub_Callback(hObject, eventdata, handles)
function Hub_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

%% Shaft tilt - text box
function Shaft_Tilt_textbox_Callback(hObject, eventdata, handles)
if isnan(str2double(get(hObject,'String')))
    set(hObject, 'String', num2str(handles.Shaft_Tilt))
end
handles.Shaft_Tilt = str2double(get(hObject,'String'));
guidata(hObject, handles);
function Shaft_Tilt_textbox_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

%% Nose cone length - text box
function Nosecone_Length_textbox_Callback(hObject, eventdata, handles)
if str2double(get(hObject,'String')) < 0
    set(hObject, 'String', '0')
elseif isnan(str2double(get(hObject,'String')))
    set(hObject, 'String', num2str(handles.Nosecone_Length))
end
handles.Nosecone_Length = str2double(get(hObject,'String'));
guidata(hObject, handles);
function Nosecone_Length_textbox_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

%% Plot geometry
function PlotButton_Callback(hObject, eventdata, handles)

% Extract nacelle geometry from input fields
Nacelle_Length = handles.Nacelle_Length;
Nacelle_Diameter = handles.Nacelle_Diameter;
Hub_Overhang = handles.Hub_Overhang;
Shaft_Tilt = handles.Shaft_Tilt;
Blade_Chord = handles.Blade_Chord;
Tower_OuterDiameter = handles.Tower_OuterDiameter;
NBlades = handles.NBlades;
Blade_Cone = handles.Blade_Cone;
Nosecone_Length = handles.Nosecone_Length;

% Color scheme
EdgeColor = 'none';
White = [240, 240, 240]/255;
Lightgrey = [174, 174, 174]/255;
Lightergrey = [200, 200, 200]/255;
Grey = [120, 120, 120]/255;
Yellow = [249, 178, 51]/255;

% Set axis
Plot = figure();
set(Plot, 'Name', 'Nacelle plot')
view(-45,180/pi*atan(sin(pi/4)))
light
lightangle(0, 45)
axis equal
axis off
hold on

N = 200 + 1;
t = Shaft_Tilt*pi/180;
Ry = [cos(t), 0, sin(t); ...
      0,      1, 0; ...
     -sin(t), 0, cos(t)];
if get(handles.Nacelle, 'Value') == 1
    
    x = [zeros(1,17); ones(1,17)] * Nacelle_Length - Hub_Overhang + 0.3 + 0.5*Blade_Chord(1);
    y = repmat([-1, -0.9, 0.9, 1, 1, 0.95, 0.95, 1, 1, 0.9, -0.9, -1, -1, -0.95, -0.95, -1, -1], [2,1]) * Nacelle_Diameter/2;
    z = repmat([0.9, 1, 1, 0.9, 0.1, 0.1, -0.1, -0.1, -0.9, -1, -1, -0.9, -0.1, -0.1, 0.1, 0.1, 0.9], [2,1]) * Nacelle_Diameter/2;
    x(2,:) = x(2,:) + 0.5*[0.9, 1, 1, 0.9, 0.1, 0.1, -0.1, -0.1, -0.9, -1, -1, -0.9, -0.1, -0.1, 0.1, 0.1, 0.9];
    z(2,:) = 7/8*z(2,:);
    A = [reshape(x,1,[]); reshape(y,1,[]); reshape(z,1,[])]; 
    A = Ry * A;
    x = reshape(A(1,:),size(x));
    y = reshape(A(2,:),size(x));
    z = reshape(A(3,:),size(z));
    surf(x,y,z, ...
        'FaceColor', White, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    patch(x(1,:),y(1,:),z(1,:), 'g', ...
        'FaceColor', White, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    patch(x(end,:),y(end,:),z(end,:), 'g', ...
        'FaceColor', White, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    
    dx = - Hub_Overhang + 0.3 + 0.5*Blade_Chord(1) + 0.25*Nacelle_Length;
    dz = Nacelle_Diameter/2*0.9;
    vert = [[-1 1 1 -1 -1 1 1 -1] * 1/2 + dx; ...
            [-1 -1 1 1 -1 -1 1 1] * 1/2; ...
            [-1 -1 -1 -1 1 1 1 1] * 1/4];
    vert = Ry * vert;
    vert(3,:) = vert(3,:) + dz;
    faces = [1 2 6 5; 2 3 7 6; 3 4 8 7; 4 1 5 8; 1 2 3 4; 5 6 7 8];
    patch('Vertices', vert', 'Faces', faces, ...
        'FaceColor', Lightergrey, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    vert = [[-1 1 1 -1 -1 1 1 -1] * 1/2 * 0.8 + dx; ...
            [-1 -1 1 1 -1 -1 1 1] * 1/2 * 0.8; ...
            [-1 -1 -1 -1 1 1 1 1] * 1/4];
    vert = Ry * vert;
    vert(3,:) = vert(3,:) + dz+0.01;
    faces = [1 2 6 5; 2 3 7 6; 3 4 8 7; 4 1 5 8; 1 2 3 4; 5 6 7 8];
    patch('Vertices', vert', 'Faces', faces, ...
        'FaceColor', White, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    
    [x,y,z] = cylinder([1 0.9 0.9]*Nacelle_Diameter/2,N-1);
    z = z*0.3 - Hub_Overhang + 0.5*Blade_Chord(1);
    A = [reshape(z,1,[]); reshape(x,1,[]); reshape(y,1,[])]; 
    A = Ry * A;
    x = reshape(A(1,:),3,N);
    y = reshape(A(2,:),3,N);
    z = reshape(A(3,:),3,N);
    surf(x,y,z, ...
        'FaceColor', Grey, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    
elseif get(handles.Nacelle, 'Value') == 2
    
    Nx = 50;
    R = Nacelle_Diameter/2;
    r = repmat(R*sin(linspace(0,pi/2,Nx)),[N,1]);
    azi = repmat(linspace(0,2*pi,N)',[1,Nx]);
    x = repmat(cos(linspace(0,pi/2,Nx)),[N,1]) * (Nacelle_Length-0.4) + 0.3 - Hub_Overhang  + 0.5*Blade_Chord(1);
    y = r.*cos(azi);
    z = r.*sin(azi);
    A = [reshape(x,1,[]); reshape(y,1,[]); reshape(z,1,[])]; 
    A = Ry * A;
    x = reshape(A(1,:),N,Nx);
    y = reshape(A(2,:),N,Nx);
    z = reshape(A(3,:),N,Nx);
    surf(x,y,z, ...
        'FaceColor', White, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    
    dx = - Hub_Overhang + 0.3 + 0.5*Blade_Chord(1) + 1.5;
    dz = Nacelle_Diameter/2*0.9;
    vert = [[-1 1 1 -1 -1 1 1 -1] * 1/2 + dx; ...
            [-1 -1 1 1 -1 -1 1 1] * 1/2; ...
            [-1 -1 -1 -1 1 1 1 1] * 1/4];
    vert = Ry * vert;
    vert(3,:) = vert(3,:) + dz;
    faces = [1 2 6 5; 2 3 7 6; 3 4 8 7; 4 1 5 8; 1 2 3 4; 5 6 7 8];
    patch('Vertices', vert', 'Faces', faces, ...
        'FaceColor', Lightergrey, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    vert = [[-1 1 1 -1 -1 1 1 -1] * 1/2 * 0.8 + dx; ...
            [-1 -1 1 1 -1 -1 1 1] * 1/2 * 0.8; ...
            [-1 -1 -1 -1 1 1 1 1] * 1/4];
    vert = Ry * vert;
    vert(3,:) = vert(3,:) + dz+0.01;
    faces = [1 2 6 5; 2 3 7 6; 3 4 8 7; 4 1 5 8; 1 2 3 4; 5 6 7 8];
    patch('Vertices', vert', 'Faces', faces, ...
        'FaceColor', White, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    
    [x,y,z] = cylinder([1 0.9 0.9 1]*Nacelle_Diameter/2,N-1);
    z = z*0.3 - Hub_Overhang + 0.5*Blade_Chord(1);
    A = [reshape(z,1,[]); reshape(x,1,[]); reshape(y,1,[])]; 
    A = Ry * A;
    x = reshape(A(1,:),4,N);
    y = reshape(A(2,:),4,N);
    z = reshape(A(3,:),4,N);
    surf(x,y,z, ...
        'FaceColor', Grey, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')

elseif get(handles.Nacelle, 'Value') == 3
    
    [x,y,z] = cylinder([1 2/3]*Nacelle_Diameter/2,N-1);
    z = z * (Nacelle_Length-0.4) + 0.3 - Hub_Overhang  + 0.5*Blade_Chord(1);
    A = [reshape(z,1,[]); reshape(x,1,[]); reshape(y,1,[])]; 
    A = Ry * A;
    x = reshape(A(1,:),2,N);
    y = reshape(A(2,:),2,N);
    z = reshape(A(3,:),2,N);
    surf(x,y,z, ...
        'FaceColor', White, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    patch(x(end,:),y(end,:),z(end,:), 'g', ...
        'FaceColor', White, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    
    dx = - Hub_Overhang + 0.3 + 0.5*Blade_Chord(1) + 0.25*Nacelle_Length;
    dz = Nacelle_Diameter/2*0.85;
    vert = [[-1 1 1 -1 -1 1 1 -1] * 1/2 + dx; ...
            [-1 -1 1 1 -1 -1 1 1] * 1/2; ...
            [-1 -1 -1 -1 1 1 1 1] * 1/4];
    vert = Ry * vert;
    vert(3,:) = vert(3,:) + dz;
    faces = [1 2 6 5; 2 3 7 6; 3 4 8 7; 4 1 5 8; 1 2 3 4; 5 6 7 8];
    patch('Vertices', vert', 'Faces', faces, ...
        'FaceColor', Lightergrey, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    vert = [[-1 1 1 -1 -1 1 1 -1] * 1/2 * 0.8 + dx; ...
            [-1 -1 1 1 -1 -1 1 1] * 1/2 * 0.8; ...
            [-1 -1 -1 -1 1 1 1 1] * 1/4];
    vert = Ry * vert;
    vert(3,:) = vert(3,:) + dz+0.01;
    faces = [1 2 6 5; 2 3 7 6; 3 4 8 7; 4 1 5 8; 1 2 3 4; 5 6 7 8];
    patch('Vertices', vert', 'Faces', faces, ...
        'FaceColor', White, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    
    [x,y,z] = cylinder([1 0.9 0.9 1]*Nacelle_Diameter/2,N-1);
    z = z*0.3 - Hub_Overhang + 0.5*Blade_Chord(1);
    A = [reshape(z,1,[]); reshape(x,1,[]); reshape(y,1,[])]; 
    A = Ry * A;
    x = reshape(A(1,:),4,N);
    y = reshape(A(2,:),4,N);
    z = reshape(A(3,:),4,N);
    surf(x,y,z, ...
        'FaceColor', Grey, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    
elseif get(handles.Nacelle, 'Value') == 4
    
    [x,y,z] = cylinder([1 1]*Nacelle_Diameter/2,N-1);
    z = z * (Nacelle_Length-0.4) + 0.3 - Hub_Overhang  + 0.5*Blade_Chord(1);
    dx = max(z(:));
    A = [reshape(z,1,[]); reshape(x,1,[]); reshape(y,1,[])]; 
    A = Ry * A;
    x = reshape(A(1,:),2,N);
    y = reshape(A(2,:),2,N);
    z = reshape(A(3,:),2,N);
    surf(x,y,z, ...
        'FaceColor', White, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    patch(x(1,:),y(1,:),z(1,:), 'g', ...
        'FaceColor', White, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    patch(x(end,:),y(end,:),z(end,:), 'g', ...
        'FaceColor', White, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    [x,y,z] = cylinder([1 1]*Tower_OuterDiameter(end)/2,N-1);
    z = dx - z * dx;
    A = [reshape(z,1,[]); reshape(x,1,[]); reshape(y,1,[])]; 
    A = Ry * A;
    x = reshape(A(1,:),2,N);
    y = reshape(A(2,:),2,N);
    z = reshape(A(3,:),2,N);
    surf(x,y,z, ...
        'FaceColor', White, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    [x,y,z] = sphere(N-1);
    x = x * Tower_OuterDiameter(end)/2;
    y = y * Tower_OuterDiameter(end)/2;
    z = z * Tower_OuterDiameter(end)/2;
    surf(x,y,z, ...
        'FaceColor', White, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    [x,y,z] = cylinder([1 0.9 0.9 1]*min(Blade_Chord(1), Tower_OuterDiameter(end)/2),N-1);
    z = z*0.3 - Hub_Overhang + 0.5*Blade_Chord(1);
    A = [reshape(z,1,[]); reshape(x,1,[]); reshape(y,1,[])]; 
    A = Ry * A;
    x = reshape(A(1,:),4,N);
    y = reshape(A(2,:),4,N);
    z = reshape(A(3,:),4,N);
    surf(x,y,z, ...
        'FaceColor', Grey, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    
elseif get(handles.Nacelle, 'Value') == 5
    
    x = [zeros(1,17); ones(1,17)] * Nacelle_Length - Hub_Overhang + 0.3 + 0.5*Blade_Chord(1);
    y = repmat([-1, -0.9, 0.9, 1, 1, 0.95, 0.95, 1, 1, 0.9, -0.9, -1, -1, -0.95, -0.95, -1, -1], [2,1]) * Nacelle_Diameter/2;
    z = repmat([0.9, 1, 1, 0.9, 0.1, 0.1, -0.1, -0.1, -0.9, -1, -1, -0.9, -0.1, -0.1, 0.1, 0.1, 0.9], [2,1]) * Nacelle_Diameter/2;
    x(2,:) = x(2,:) + 0.5*[0.9, 1, 1, 0.9, 0.1, 0.1, -0.1, -0.1, -0.9, -1, -1, -0.9, -0.1, -0.1, 0.1, 0.1, 0.9];
    z(2,:) = 7/8*z(2,:);
    A = [reshape(x,1,[]); reshape(y,1,[]); reshape(z,1,[])]; 
    A = Ry * A;
    x = reshape(A(1,:),size(x));
    y = reshape(A(2,:),size(x));
    z = reshape(A(3,:),size(z));
    surf(x,y,z, ...
        'FaceColor', White, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    patch(x(1,:),y(1,:),z(1,:), 'g', ...
        'FaceColor', White, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    patch(x(end,:),y(end,:),z(end,:), 'g', ...
        'FaceColor', White, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    
    dx = - Hub_Overhang + 0.3 + 0.5*Blade_Chord(1) + 0.25*Nacelle_Length;
    dz = Nacelle_Diameter/2*0.9;
    vert = [[-1 1 1 -1 -1 1 1 -1] * 1/2 + dx; ...
            [-1 -1 1 1 -1 -1 1 1] * 1/2; ...
            [-1 -1 -1 -1 1 1 1 1] * 1/4];
    vert = Ry * vert;
    vert(3,:) = vert(3,:) + dz;
    faces = [1 2 6 5; 2 3 7 6; 3 4 8 7; 4 1 5 8; 1 2 3 4; 5 6 7 8];
    patch('Vertices', vert', 'Faces', faces, ...
        'FaceColor', Lightergrey, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    vert = [[-1 1 1 -1 -1 1 1 -1] * 1/2 * 0.8 + dx; ...
            [-1 -1 1 1 -1 -1 1 1] * 1/2 * 0.8; ...
            [-1 -1 -1 -1 1 1 1 1] * 1/4];
    vert = Ry * vert;
    vert(3,:) = vert(3,:) + dz+0.01;
    faces = [1 2 6 5; 2 3 7 6; 3 4 8 7; 4 1 5 8; 1 2 3 4; 5 6 7 8];
    patch('Vertices', vert', 'Faces', faces, ...
        'FaceColor', White, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    
    x = [0, 0, 2, 2, 2, 2, 0, 0; 2, 2, 3.5, 3.5, 3.5, 3.5, 2, 2] + 0.5*Nacelle_Length - Hub_Overhang + 0.3 + 0.5*Blade_Chord(1);
    y = [1, 1, 1, 0.9, -0.9, -1, -1, -1; 1, 1, 1, 0.9, -0.9, -1, -1, -1] * Nacelle_Diameter/2;
    z = [0.1, 0.1, 0.9, 1, 1, 0.9, 0.1, 0.1; 0.1, 0.1, 0.9, 1, 1, 0.9, 0.1, 0.1] * Nacelle_Diameter * 3/4;
    y(:,2:3) = y(:,2:3) + 0.25;
    y(:,6:7) = y(:,6:7) - 0.25;
    A = [reshape(x,1,[]); reshape(y,1,[]); reshape(z,1,[])]; 
    A = Ry * A;
    x = reshape(A(1,:),size(x));
    y = reshape(A(2,:),size(y));
    z = reshape(A(3,:),size(z));
    surf(x,y,z, ...
        'FaceColor', White, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    x_ = [0, 0, 2, 2, 2, 2, 0, 0; 2, 2, 3.5, 3.5, 3.5, 3.5, 2, 2] + 0.5*Nacelle_Length - Hub_Overhang + 0.3 + 0.5*Blade_Chord(1);
    y_ = [1, 1, 1, 0.9, -0.9, -1, -1, -1; 1, 1, 1, 0.9, -0.9, -1, -1, -1] * Nacelle_Diameter/2 + 0.2*[0, -1, -1, -1, 1, 1, 1, 0; 0, -1, -1, -1, -1, 1, 1, 0];
    z_ = [0.1, 0.1, 0.9, 1, 1, 0.9, 0.1, 0.1; 0.1, 0.1, 0.9, 1, 1, 0.9, 0.1, 0.1] * Nacelle_Diameter * 3/4 + 0.2*[0, 0, -1, -1, -1, -1, 0, 0; 0, 0, -1, -1, -1, -1, 0, 0];
    y_(:,2:3) = y_(:,2:3) + 0.25;
    y_(:,6:7) = y_(:,6:7) - 0.25;
    A = [reshape(x_,1,[]); reshape(y_,1,[]); reshape(z_,1,[])]; 
    A = Ry * A;
    x_ = reshape(A(1,:),size(x_));
    y_ = reshape(A(2,:),size(y_));
    z_ = reshape(A(3,:),size(z_));
    surf(x_,y_,z_, ...
        'FaceColor', Lightgrey, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    patch(...
        [x(1,:), flip(x_(1,:))], ...
        [y(1,:), flip(y_(1,:))], ...
        [z(1,:), flip(z_(1,:))], ...
        'g', 'FaceColor', White, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    patch(...
        [x(end,:), flip(x_(end,:))], ...
        [y(end,:), flip(y_(end,:))], ...
        [z(end,:), flip(z_(end,:))], ...
        'g', 'FaceColor', White, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    
    [x,y,z] = cylinder([1 0.9 0.9]*Nacelle_Diameter/2,N-1);
    z = z*0.3 - Hub_Overhang + 0.5*Blade_Chord(1);
    A = [reshape(z,1,[]); reshape(x,1,[]); reshape(y,1,[])]; 
    A = Ry * A;
    x = reshape(A(1,:),3,N);
    y = reshape(A(2,:),3,N);
    z = reshape(A(3,:),3,N);
    surf(x,y,z, ...
        'FaceColor', Grey, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    
elseif get(handles.Nacelle, 'Value') == 6
    
    x = [zeros(1,17); ones(1,17)] * Nacelle_Length - Hub_Overhang + 0.3 + 0.5*Blade_Chord(1);
    y = repmat([-1, -0.9, 0.9, 1, 1, 0.95, 0.95, 1, 1, 0.9, -0.9, -1, -1, -0.95, -0.95, -1, -1], [2,1]) * Nacelle_Diameter/2;
    z = repmat([0.9, 1, 1, 0.9, 0.1, 0.1, -0.1, -0.1, -0.9, -1, -1, -0.9, -0.1, -0.1, 0.1, 0.1, 0.9], [2,1]) * Nacelle_Diameter/2;
    x(2,:) = x(2,:) + 0.5*[0.9, 1, 1, 0.9, 0.1, 0.1, -0.1, -0.1, -0.9, -1, -1, -0.9, -0.1, -0.1, 0.1, 0.1, 0.9];
    z(2,:) = 7/8*z(2,:);
    A = [reshape(x,1,[]); reshape(y,1,[]); reshape(z,1,[])]; 
    A = Ry * A;
    x = reshape(A(1,:),size(x));
    y = reshape(A(2,:),size(x));
    z = reshape(A(3,:),size(z));
    surf(x,y,z, ...
        'FaceColor', White, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    patch(x(1,:),y(1,:),z(1,:), 'g', ...
        'FaceColor', White, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    patch(x(end,:),y(end,:),z(end,:), 'g', ...
        'FaceColor', White, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    
    dx = - Hub_Overhang + 0.3 + 0.5*Blade_Chord(1) + 0.25*Nacelle_Length;
    dz = Nacelle_Diameter/2*0.9;
    vert = [[-1 1 1 -1 -1 1 1 -1] * 1/2 + dx; ...
            [-1 -1 1 1 -1 -1 1 1] * 1/2; ...
            [-1 -1 -1 -1 1 1 1 1] * 1/4];
    vert = Ry * vert;
    vert(3,:) = vert(3,:) + dz;
    faces = [1 2 6 5; 2 3 7 6; 3 4 8 7; 4 1 5 8; 1 2 3 4; 5 6 7 8];
    patch('Vertices', vert', 'Faces', faces, ...
        'FaceColor', Lightergrey, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    vert = [[-1 1 1 -1 -1 1 1 -1] * 1/2 * 0.8 + dx; ...
            [-1 -1 1 1 -1 -1 1 1] * 1/2 * 0.8; ...
            [-1 -1 -1 -1 1 1 1 1] * 1/4];
    vert = Ry * vert;
    vert(3,:) = vert(3,:) + dz+0.01;
    faces = [1 2 6 5; 2 3 7 6; 3 4 8 7; 4 1 5 8; 1 2 3 4; 5 6 7 8];
    patch('Vertices', vert', 'Faces', faces, ...
        'FaceColor', White, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    
    dx = - Hub_Overhang + 0.3 + 0.5*Blade_Chord(1) + (Nacelle_Length-1.5);
    dz = 0.5 + Nacelle_Diameter/2*0.9;
    vert = [[-1 1 1 -1 -1 1 1 -1] * 2 + dx*cos(t); ...
            [-1 -1 1 1 -1 -1 1 1] * 3/2; ...
            [-1 -1 -1 -1 0 0 0 0] * 0.25 + dz - dx*sin(t)];
    faces = [1 2 6 5; 2 3 7 6; 3 4 8 7; 4 1 5 8; 1 2 3 4; 5 6 7 8];
    patch('Vertices', vert', 'Faces', faces, ...
        'FaceColor', Lightgrey, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    x = repmat([-1, 1, 1, -1, -1] * 2 + dx*cos(t), [2,1]);
    y = repmat([1, 1, -1, -1, 1] * 3/2, [2,1]);
    z = [zeros(1,5); ones(1,5)] * 0.25 + dz - dx*sin(t);
    surf(x,y,z, ...
        'FaceColor', Lightgrey, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    [x,y,z] = cylinder(0.1,12);
    x = x + dx*cos(t);
    z = -z - 0.25 + dz  - dx*sin(t);
    for i = [-1, 1]
        for j = [-1, 1]
            surf(x+i,y+j,z, ...
                'FaceColor', Grey, ...
                'EdgeColor', EdgeColor, ...
                'AmbientStrength', 0.5, ...
                'DiffuseStrength', 0.5, ...
                'SpecularStrength', 0.5, ...
                'BackFaceLighting', 'reverselit')
        end
    end
    
    [x,y,z] = cylinder([1 0.9 0.9]*Nacelle_Diameter/2,N-1);
    z = z*0.3 - Hub_Overhang + 0.5*Blade_Chord(1);
    A = [reshape(z,1,[]); reshape(x,1,[]); reshape(y,1,[])]; 
    A = Ry * A;
    x = reshape(A(1,:),3,N);
    y = reshape(A(2,:),3,N);
    z = reshape(A(3,:),3,N);
    surf(x,y,z, ...
        'FaceColor', Grey, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    
elseif get(handles.Nacelle, 'Value') == 7

    x = [zeros(1,17); ones(1,17)] * Nacelle_Length - Hub_Overhang + 0.3 + 0.5*Blade_Chord(1);
    y = repmat([-1, -0.9, 0.9, 1, 1, 0.95, 0.95, 1, 1, 0.9, -0.9, -1, -1, -0.95, -0.95, -1, -1], [2,1]) * Nacelle_Diameter/2;
    z = repmat([0.9, 1, 1, 0.9, 0.1, 0.1, -0.1, -0.1, -0.9, -1, -1, -0.9, -0.1, -0.1, 0.1, 0.1, 0.9], [2,1]) * Nacelle_Diameter/2;
    x(2,:) = x(2,:) + 0.5*[0.9, 1, 1, 0.9, 0.1, 0.1, -0.1, -0.1, -0.9, -1, -1, -0.9, -0.1, -0.1, 0.1, 0.1, 0.9];
    z(2,:) = 7/8*z(2,:);
    A = [reshape(x,1,[]); reshape(y,1,[]); reshape(z,1,[])]; 
    A = Ry * A;
    x = reshape(A(1,:),size(x));
    y = reshape(A(2,:),size(x));
    z = reshape(A(3,:),size(z));
    z(2,[1,4,17]) = 0.9*Nacelle_Diameter/2;
    z(2,2:3) = Nacelle_Diameter/2;
    surf(x,y,z, ...
        'FaceColor', White, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    patch(x(1,:),y(1,:),z(1,:), 'g', ...
        'FaceColor', White, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    patch(x(end,:),y(end,:),z(end,:), 'g', ...
        'FaceColor', White, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    x = [-1-sqrt(2), -1, 1, 1+sqrt(2), 1+sqrt(2), 1, -1, -1-sqrt(2), -1-sqrt(2)] + 1+sqrt(2);
    y = [1, 1+sqrt(2), 1+sqrt(2), 1, -1, -1-sqrt(2), -1-sqrt(2), -1, 1];
    x = repmat(x,[2,1])*2.5 - Hub_Overhang + 0.3 + 0.5*Blade_Chord(1) + 1;
    y = repmat(y,[2,1])*2.5;
    z = [zeros(1,9); ones(1,9)]*0.5 + Nacelle_Diameter/2;
    surf(x,y,z, ...
        'FaceColor', Grey, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    patch(x(1,:),y(1,:),z(1,:), 'g', ...
        'FaceColor', Grey, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    patch(x(end,:),y(end,:),z(end,:), 'g', ...
        'FaceColor', Grey, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    dx = - Hub_Overhang + 0.3 + 0.5*Blade_Chord(1) + 1 + (1+sqrt(2))*2.5;
    x = ([0, 0, 0, 0; 1, 1, 1, 1] - 0.5) * 0.5 + dx;
    y = [0, 1, 0, 0; 0, 1, 0, 0];
    z = [-1, 0, 0, -1; -1, 0, 0, -1] + Nacelle_Diameter/2;
    if Nacelle_Diameter < 10
        for i = [-1 1]
            for j = [-1 1]
                surf(x + 1.5*i,y*j + Nacelle_Diameter/2*j,z, ...
                    'FaceColor', Lightgrey, ...
                    'EdgeColor', EdgeColor, ...
                    'AmbientStrength', 0.5, ...
                    'DiffuseStrength', 0.5, ...
                    'SpecularStrength', 0.5, ...
                    'BackFaceLighting', 'reverselit')
            end
        end
    end
    h = 0.75;
    q = linspace(0,2*pi,25);
    x = [(5+2/3*h)*cos(q); 5*cos(q)];
    y = [(5+2/3*h)*sin(q); 5*sin(q)];
    z = zeros(size(x));
    x = x + dx;
    z = z+0.01 + 0.5 + Nacelle_Diameter/2;
    surf(x,y,z, ...
        'FaceColor', Yellow, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    x = [1, 1, 0, 0, 1, 1, -1, -1, 0, 0, -1, -1, 1]*2 + [0, 0, h/2, h/2, 0, 0, 0, 0, -h/2, -h/2, 0, 0, 0];
    y = [-1, -1, -1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1]*2 + [0, h, h, -h, -h, 0, 0, -h, -h, h, h, 0, 0];
    z = zeros(size(x));
    x = x + dx;
    z = z+0.01 + 0.5 + Nacelle_Diameter/2;
    patch(x,y,z, 'g', ...
        'FaceColor', Yellow, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    
    [x,y,z] = cylinder([1 0.9 0.9]*Nacelle_Diameter/2,N-1);
    z = z*0.3 - Hub_Overhang + 0.5*Blade_Chord(1);
    A = [reshape(z,1,[]); reshape(x,1,[]); reshape(y,1,[])]; 
    A = Ry * A;
    x = reshape(A(1,:),3,N);
    y = reshape(A(2,:),3,N);
    z = reshape(A(3,:),3,N);
    surf(x,y,z, ...
        'FaceColor', Grey, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    
end

% Plot nose cone
if get(handles.Nacelle, 'Value') == 4
    R = min(Blade_Chord(1)*3/4, Tower_OuterDiameter(end)/2);
else
    R = Nacelle_Diameter/2;
end
if get(handles.Hub, 'Value') == 1
    
    Nx = 50;
    r = repmat(R*sin(linspace(0,pi/2,Nx)),[N,1]);
    azi = repmat(linspace(0,2*pi,N)',[1,Nx]);
    x = 0.5*Blade_Chord(1) - repmat(cos(linspace(0,pi/2,Nx)),[N,1])*Nosecone_Length - Hub_Overhang;
    y = r.*cos(azi);
    z = r.*sin(azi);

elseif get(handles.Hub, 'Value') == 2
    
    Nx = 4;
    [x_,y_,z_] = cylinder([1, 0.99]*R,N-1);
    x = z_'; y = x_'; z = y_';
    x = [x * 0.9, x(:,end), x(:,end)];
    y = [y, y(:,end) * 0.9, y(:,end) * 0];
    z = [z, z(:,end) * 0.9, z(:,end) * 0];
    x = 0.5*Blade_Chord(1) - x*Nosecone_Length - Hub_Overhang;

elseif get(handles.Hub, 'Value') == 3
    
    Nx = 3;
    [x_,y_,z_] = cylinder([1, 0.99]*R,N-1);
    x = z_'; y = x_'; z = y_';
    x = [x*0.5*Blade_Chord(1)/Nosecone_Length, x(:,end)];
    y = [y, y(:,end) * 0];
    z = [z, z(:,end) * 0];
    x = 0.5*Blade_Chord(1) - x*Nosecone_Length - Hub_Overhang;

elseif get(handles.Hub, 'Value') == 4
    
    Nx = 50;
    rho = (R^2 + Nosecone_Length^2)/(2*R);
    x = linspace(0,Nosecone_Length,Nx);
    r = repmat(sqrt(rho^2 - (Nosecone_Length-x).^2) + R - rho,[N,1]);
    azi = repmat(linspace(0,2*pi,N)',[1,Nx]);
    x = repmat(x-Nosecone_Length,[N,1]) + 0.5*Blade_Chord(1) - Hub_Overhang;
    y = r.*cos(azi);
    z = r.*sin(azi);
    
end
A = [reshape(x,1,[]); reshape(y,1,[]); reshape(z,1,[])]; 
A = Ry * A;
x = reshape(A(1,:),N,Nx);
y = reshape(A(2,:),N,Nx);
z = reshape(A(3,:),N,Nx);
surf(x,y,z, ...
    'FaceColor', Lightergrey, ...
    'EdgeColor', EdgeColor, ...
    'AmbientStrength', 0.5, ...
    'DiffuseStrength', 0.5, ...
    'SpecularStrength', 0.5, ...
    'BackFaceLighting', 'reverselit')

% Plot blades
o = 2*pi/NBlades;
t = Shaft_Tilt*pi/180;
Ry = [cos(t), 0, sin(t); ...
      0,      1, 0; ...
     -sin(t), 0, cos(t)];
c = -Blade_Cone*pi/180;
Rc = [cos(c), 0, sin(c); ...
      0,      1, 0; ...
     -sin(c), 0, cos(c)];
if NBlades == 1
    do = pi/2;
else
    do = pi - pi/NBlades;
end
for B = 1:NBlades
    Rx = [1, 0,      0; ...
          0, cos(B*o + do),-sin(B*o + do); ...
          0, sin(B*o + do), cos(B*o + do)];
    [x,y,z] = cylinder(Blade_Chord(1)/2,400);
    z = z*(R+1/3);
    A = [reshape(x,1,[]); reshape(y,1,[]); reshape(z,1,[])];
    A = Rc * A;
    A(1,:) = A(1,:) - Hub_Overhang;
    A = Ry * Rx * A;
    N = size(x);
    x = reshape(A(1,:),N);
    y = reshape(A(2,:),N);
    z = reshape(A(3,:),N);
    surf(x,y,z, ...
        'FaceColor', White, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit');
    
    [x_,y_,z_] = cylinder(0.8*Blade_Chord(1)/2,400);
    z_ = R + z_*1/3;
    if get(handles.Hub, 'Value') == 2
        z_(1,:) = z_(1,:) + 0.1;
    end
    A = [reshape(x_,1,[]); reshape(y_,1,[]); reshape(z_,1,[])];
    A = Rc * A;
    A(1,:) = A(1,:) - Hub_Overhang;
    A = Ry * Rx * A;
    N = size(x_);
    x_ = reshape(A(1,:),N);
    y_ = reshape(A(2,:),N);
    z_ = reshape(A(3,:),N);
    surf(x_,y_,z_, ...
        'FaceColor', White, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit');
    
    patch(...
        [x(end,:), flip(x_(end,:))], ...
        [y(end,:), flip(y_(end,:))], ...
        [z(end,:), flip(z_(end,:))], ...
        'g', 'FaceColor', Lightergrey, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    
    patch(...
        x_(1,:), ...
        y_(1,:), ...
        z_(1,:), ...
        'g', 'FaceColor', Lightgrey, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    
    R_ = 0.9/2*Blade_Chord(1);
    r = 0.05/2*Blade_Chord(1);
    [x_,y_,z_] = cylinder([r r],12);
    for q = pi/15:pi/15:2*pi
        x = x_ + R_*cos(q);
        y = y_ + R_*sin(q);
        z = 0.3*z_ + R + 1/3;
        A = [reshape(x,1,[]); reshape(y,1,[]); reshape(z,1,[])];
        A = Rc * A;
        A(1,:) = A(1,:) - Hub_Overhang;
        A = Ry * Rx * A;
        N = size(x_);
        x = reshape(A(1,:),N);
        y = reshape(A(2,:),N);
        z = reshape(A(3,:),N);
        surf(x,y,z, ...
            'FaceColor', Grey, ...
            'EdgeColor', EdgeColor, ...
            'AmbientStrength', 0.5, ...
            'DiffuseStrength', 0.5, ...
            'SpecularStrength', 0.5, ...
            'BackFaceLighting', 'reverselit')
        patch(x(end,:), y(end,:), z(end,:), ...
            'g', 'FaceColor', Grey, ...
            'EdgeColor', EdgeColor, ...
            'AmbientStrength', 0.5, ...
            'DiffuseStrength', 0.5, ...
            'SpecularStrength', 0.5, ...
            'BackFaceLighting', 'reverselit')
    end
    
end

if NBlades == 1
    
    c = Blade_Cone*pi/180;
    Rc = [cos(c), 0, sin(c); ...
          0,      1, 0; ...
         -sin(c), 0, cos(c)];
    do = do + pi;
    Rx = [1, 0,      0; ...
          0, cos(B*o + do),-sin(B*o + do); ...
          0, sin(B*o + do), cos(B*o + do)];
    [x,y,z] = cylinder(Blade_Chord(1)/2*2/3,400);
    z = z*(R+1/3);
    A = [reshape(x,1,[]); reshape(y,1,[]); reshape(z,1,[])];
    A = Rc * A;
    A(1,:) = A(1,:) - Hub_Overhang;
    A = Ry * Rx * A;
    N = size(x);
    x = reshape(A(1,:),N);
    y = reshape(A(2,:),N);
    z = reshape(A(3,:),N);
    surf(x,y,z, ...
        'FaceColor', White, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit');
    
    [x_,y_,z_] = cylinder(0.8*Blade_Chord(1)/2*2/3,400);
    z_ = z_*1/3 + R;
    if get(handles.Hub, 'Value') == 2
        z_(1,:) = z_(1,:) + 0.1;
    end
    A = [reshape(x_,1,[]); reshape(y_,1,[]); reshape(z_,1,[])];
    A = Rc * A;
    A(1,:) = A(1,:) - Hub_Overhang;
    A = Ry * Rx * A;
    N = size(x_);
    x_ = reshape(A(1,:),N);
    y_ = reshape(A(2,:),N);
    z_ = reshape(A(3,:),N);
    surf(x_,y_,z_, ...
        'FaceColor', White, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit');
    
    patch(...
        [x(end,:), flip(x_(end,:))], ...
        [y(end,:), flip(y_(end,:))], ...
        [z(end,:), flip(z_(end,:))], ...
        'g', 'FaceColor', Lightergrey, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    
    patch(...
        x_(1,:), ...
        y_(1,:), ...
        z_(1,:), ...
        'g', 'FaceColor', Lightgrey, ...
        'EdgeColor', EdgeColor, ...
        'AmbientStrength', 0.5, ...
        'DiffuseStrength', 0.5, ...
        'SpecularStrength', 0.5, ...
        'BackFaceLighting', 'reverselit')
    
    R_ = 0.9/2*Blade_Chord(1) * 2/3;
    r = 0.05/2*Blade_Chord(1) * 2/3;
    [x_,y_,z_] = cylinder([r r],12);
    for q = pi/15:pi/15:2*pi
        x = x_ + R_*cos(q);
        y = y_ + R_*sin(q);
        z = 0.3*z_ + R + 1/3;
        A = [reshape(x,1,[]); reshape(y,1,[]); reshape(z,1,[])];
        A = Rc * A;
        A(1,:) = A(1,:) - Hub_Overhang;
        A = Ry * Rx * A;
        N = size(x_);
        x = reshape(A(1,:),N);
        y = reshape(A(2,:),N);
        z = reshape(A(3,:),N);
        surf(x,y,z, ...
            'FaceColor', Grey, ...
            'EdgeColor', EdgeColor, ...
            'AmbientStrength', 0.5, ...
            'DiffuseStrength', 0.5, ...
            'SpecularStrength', 0.5, ...
            'BackFaceLighting', 'reverselit')
        patch(x(1,:), y(1,:), z(1,:), ...
            'g', 'FaceColor', Grey, ...
            'EdgeColor', EdgeColor, ...
            'AmbientStrength', 0.5, ...
            'DiffuseStrength', 0.5, ...
            'SpecularStrength', 0.5, ...
            'BackFaceLighting', 'reverselit')
    end
    
end

% Tower
[x,y,z] = cylinder(Tower_OuterDiameter(end)/2,400);
z = -z*(Nacelle_Diameter/2 + 1);
surf(x,y,z, ...
    'FaceColor', White, ...
    'EdgeColor', EdgeColor, ...
    'AmbientStrength', 0.5, ...
    'DiffuseStrength', 0.5, ...
    'SpecularStrength', 0.5, ...
    'BackFaceLighting', 'reverselit');

[x_,y_,z_] = cylinder(0.95*Tower_OuterDiameter(end)/2,400);
z_ = -z_*(Nacelle_Diameter/2 + 1);
surf(x_,y_,z_, ...
    'FaceColor', White, ...
    'EdgeColor', EdgeColor, ...
    'AmbientStrength', 0.5, ...
    'DiffuseStrength', 0.5, ...
    'SpecularStrength', 0.5, ...
    'BackFaceLighting', 'reverselit');

patch(...
    [x(end,:), flip(x_(end,:))], ...
    [y(end,:), flip(y_(end,:))], ...
    [z(end,:), flip(z_(end,:))], ...
    'g', 'FaceColor', Lightergrey, ...
    'EdgeColor', EdgeColor, ...
    'AmbientStrength', 0.5, ...
    'DiffuseStrength', 0.5, ...
    'SpecularStrength', 0.5, ...
    'BackFaceLighting', 'reverselit')

patch(x_(end,:), y_(end,:), z_(end,:) + 2/3, ...
    'g', 'FaceColor', Lightgrey, ...
    'EdgeColor', EdgeColor, ...
    'AmbientStrength', 0.5, ...
    'DiffuseStrength', 0.5, ...
    'SpecularStrength', 0.5, ...
    'BackFaceLighting', 'reverselit')
