%% Calculate DEL values for the inflow profiles generated by "setupInflowFiles.m"
clear; close all; clc;
addpath bin

% Setup inflow settings
inflowSetName          = 'C2C_only';
inputData.sourceFolder = ['inflowProfiles\' inflowSetName];

% Specify correct settings and load workspace
WS          = load([inputData.sourceFolder '\workspace.mat']);
T           = WS.inputData.T;  % simulation time in seconds
dt          = WS.inputData.dt; % sampling time in seconds

% Import relevant libraries and files for FAST
load('FAST_module\Controller_parameters');   % Load FAST settings

% Evaluate DELs
[matDELs,~] = nested_calculateDELs(WS)
%
disp('Finished calculating DEL table. Saving...');
save(['..\LUT_database\' inflowSetName '.mat'],'matDELs','WS')